spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order-service-order
          uri: ${rewrite.backend.uri:http://localhost:8081}

          predicates:
            - Path=/skillbox/api/**

          filters:
            - RewritePath=/skillbox/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.gateway: TRACE


